<a href="https://colab.research.google.com/github/KitoPlayer/ON_LAB_3_4_domowe/blob/main/ON_LAB4_domowe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Zadania domowe

In [ ]:
import numpy as np

## Zadanie 1
Napisz metodę, która oblicza pole między osią $OX$ a wykresem funkcji na danym przedziale za pomocą sum Riemanna (przybliżeń prostokątami). Sprawdź jej działanie na wybranej przez siebie funkcji porównując z wynikiem całkownia symbolicznego. 

Korzystając z symbolicznych pochodnych i szukania ekstremów dobierz takie parametry do swojej funkcji, aby błąd całkowania był mniejszy niż $10^{-5}$.


## Zadanie 2
a) Zaimplementuj w postaci funkcji algorytm obliczania pierwiastka kwadratowego z $x>0$ z wykorzystaniem algorytmu Herona. Funkcja powinna przyjmować jako argumenty liczby: $x$, punkt startowy $x_0$ oraz liczbę kroków (wyrazów ciągu do obliczenia).

b) Następnie, dodaj argument `show_step` (domyślnie ustawiony jako `False`), który będzie pozwalał wyświetlać kolejne kroki przybliżenia aż do zadanego.

c) Na bazie rozwiązania z punktu a) stwórz nową funkcję, która wykona odpowiednią liczbę kroków by przybliżenie miało podaną dokładność.

# NumPy

## Zadanie 3

Stwórz dowolną tablicę liczb całkowitych ndarray z zagnieżdżonej listy. Sprawdź jej różne atrybuty. Spróbuj zamienić wszystkie liczby całkowite na zmiennoprzecinkowe.

## Zadanie 4
Skonstruuj macierz:
$$
Mat1=\begin{bmatrix}
1 &1 &0&0&0&0&0\\
1&1&0&0&0&0&0\\
0&0&0&0&0&0&0 \\
0&0&0&0&0&0&0 \\
0&0&0&0&3&0&0 \\
0&0&0&0&0&2&4 \\
0&0&0&0&0&4&2 \\
\end{bmatrix}
$$

In [ ]:
Mat1 = np.array([[ 1, 1, 0, 0, 0, 0, 0],
           [ 1, 1, 0, 0, 0, 0, 0],
           [ 0, 0, 0, 0, 0, 0, 0],
           [ 0, 0, 0, 0, 0, 0, 0],
           [ 0, 0, 0, 0, 3, 0, 0],
           [ 0, 0, 0, 0, 0, 2, 4],
           [ 0, 0, 0, 0, 0, 4, 2]])

Mat1

array([[1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 2, 4],
       [0, 0, 0, 0, 0, 4, 2]])

## Zadanie 5
W macierzy `Mat1` zamień miejscami lewy górny narożnik $4 \times 4$ z prawym dolnym $3 \times 3$ (nazwij wynik `Mat2`).

## Zadanie 6
Stwórz macierz `Mat3`, która będzie zawierała tylko elementy z `Mat2` o obu parzystych współrzędnych.

###Zadanie 5 :


In [ ]:


Mat2 = np.array([[ 1, 1, 0, 0, 0, 0, 0],
           [ 1, 1, 0, 0, 0, 0, 0],
           [ 0, 0, 0, 0, 0, 0, 0],
           [ 0, 0, 0, 0, 0, 0, 0],
           [ 0, 0, 0, 0, 3, 0, 0],
           [ 0, 0, 0, 0, 0, 2, 4],
           [ 0, 0, 0, 0, 0, 4, 2]])

Mat2

array([[1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 2, 4],
       [0, 0, 0, 0, 0, 4, 2]])

In [ ]:
Mat2[0:3, 0:3] = Mat1[4:7, 4:7]

Mat2

array([[3, 0, 0, 0, 0, 0, 0],
       [0, 2, 4, 0, 0, 0, 0],
       [0, 4, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 2, 4],
       [0, 0, 0, 0, 0, 4, 2]])

In [ ]:
Mat2[4:7, 4:7] = Mat1[0:3, 0:3]



In [ ]:

print(Mat2)
print(Mat1)


[[3 0 0 0 0 0 0]
 [0 2 4 0 0 0 0]
 [0 4 2 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0]]
[[1 1 0 0 0 0 0]
 [1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 2 4]
 [0 0 0 0 0 4 2]]


###Zadanie 6 :

In [ ]:
Mat3 = Mat2[1::2, 1::2]
Mat3

array([[2, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

## Zadanie 7
Utwórz tablicę

$$
\begin{bmatrix}
1&2&3&4\\
5&6&7&8 \\
9&10&11&12\\
13&14&15&16
\end{bmatrix}
$$

In [ ]:
lista_1 = [1, 2, 3, 4]
lista_2 = [5, 6, 7, 8]
lista_3 = [9, 10, 11, 12]
lista_4 = [13, 14, 15, 16]

tablica = [lista_1, lista_2, lista_3, lista_4]

for i in tablica:
  print(i)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]
